generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Url
    theme:                 simpla
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          url
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Links
        actions: []
        batch_actions: []
        object_actions: []
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
