<?php

/**
 * BaseTipoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * 
 * @method string      getTipo() Returns the current record's "tipo" value
 * @method TipoUsuario setTipo() Sets the current record's "tipo" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_usuario');
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}