<?php

/**
 * BaseTipoResgate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * @property string $descricao
 * @property Doctrine_Collection $Resgate
 * 
 * @method string              getTipo()      Returns the current record's "tipo" value
 * @method string              getDescricao() Returns the current record's "descricao" value
 * @method Doctrine_Collection getResgate()   Returns the current record's "Resgate" collection
 * @method TipoResgate         setTipo()      Sets the current record's "tipo" value
 * @method TipoResgate         setDescricao() Sets the current record's "descricao" value
 * @method TipoResgate         setResgate()   Sets the current record's "Resgate" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoResgate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_resgate');
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Resgate', array(
             'local' => 'id',
             'foreign' => 'tipo_resgate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}