<?php

/**
 * BaseOrcamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $valor
 * @property integer $quantidade
 * @property string $descricao
 * @property Doctrine_Collection $Campanha
 * 
 * @method float               getValor()      Returns the current record's "valor" value
 * @method integer             getQuantidade() Returns the current record's "quantidade" value
 * @method string              getDescricao()  Returns the current record's "descricao" value
 * @method Doctrine_Collection getCampanha()   Returns the current record's "Campanha" collection
 * @method Orcamento           setValor()      Sets the current record's "valor" value
 * @method Orcamento           setQuantidade() Sets the current record's "quantidade" value
 * @method Orcamento           setDescricao()  Sets the current record's "descricao" value
 * @method Orcamento           setCampanha()   Sets the current record's "Campanha" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrcamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orcamento');
        $this->hasColumn('valor', 'float', 11, array(
             'type' => 'float',
             'length' => 11,
             'scale' => '6',
             ));
        $this->hasColumn('quantidade', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Campanha', array(
             'local' => 'id',
             'foreign' => 'orcamento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}