<?php

/**
 * BaseReferalControle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $url_id
 * @property integer $resgate_id
 * @property string $ipuser
 * @property boolean $is_rescued
 * @property boolean $is_processed
 * @property datetime $data_processado
 * @property Url $Url
 * @property Resgate $Resgate
 * 
 * @method integer         getUrlId()           Returns the current record's "url_id" value
 * @method integer         getResgateId()       Returns the current record's "resgate_id" value
 * @method string          getIpuser()          Returns the current record's "ipuser" value
 * @method boolean         getIsRescued()       Returns the current record's "is_rescued" value
 * @method boolean         getIsProcessed()     Returns the current record's "is_processed" value
 * @method datetime        getDataProcessado()  Returns the current record's "data_processado" value
 * @method Url             getUrl()             Returns the current record's "Url" value
 * @method Resgate         getResgate()         Returns the current record's "Resgate" value
 * @method ReferalControle setUrlId()           Sets the current record's "url_id" value
 * @method ReferalControle setResgateId()       Sets the current record's "resgate_id" value
 * @method ReferalControle setIpuser()          Sets the current record's "ipuser" value
 * @method ReferalControle setIsRescued()       Sets the current record's "is_rescued" value
 * @method ReferalControle setIsProcessed()     Sets the current record's "is_processed" value
 * @method ReferalControle setDataProcessado()  Sets the current record's "data_processado" value
 * @method ReferalControle setUrl()             Sets the current record's "Url" value
 * @method ReferalControle setResgate()         Sets the current record's "Resgate" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReferalControle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('referal_controle');
        $this->hasColumn('url_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('resgate_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('ipuser', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_rescued', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_processed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('data_processado', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Url', array(
             'local' => 'url_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('Resgate', array(
             'local' => 'resgate_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}