<?php

/**
 * BaseValidaUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $chave
 * @property boolean $is_confirmed
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer       getUserId()       Returns the current record's "user_id" value
 * @method string        getChave()        Returns the current record's "chave" value
 * @method boolean       getIsConfirmed()  Returns the current record's "is_confirmed" value
 * @method sfGuardUser   getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method ValidaUsuario setUserId()       Sets the current record's "user_id" value
 * @method ValidaUsuario setChave()        Sets the current record's "chave" value
 * @method ValidaUsuario setIsConfirmed()  Sets the current record's "is_confirmed" value
 * @method ValidaUsuario setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseValidaUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('valida_usuario');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('chave', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_confirmed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}