<?php

/**
 * BaseUrlControle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $url_id
 * @property string $ipuser
 * @property Url $Url
 * 
 * @method integer     getUrlId()  Returns the current record's "url_id" value
 * @method string      getIpuser() Returns the current record's "ipuser" value
 * @method Url         getUrl()    Returns the current record's "Url" value
 * @method UrlControle setUrlId()  Sets the current record's "url_id" value
 * @method UrlControle setIpuser() Sets the current record's "ipuser" value
 * @method UrlControle setUrl()    Sets the current record's "Url" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUrlControle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('url_controle');
        $this->hasColumn('url_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('ipuser', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Url', array(
             'local' => 'url_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}