<?php

/**
 * BaseDadoBancario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $banco
 * @property varchar $agencia
 * @property varchar $tipo_conta
 * @property varchar $operacao
 * @property varchar $conta_numero
 * @property varchar $favorecido
 * @property varchar $cpf
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer      getUserId()       Returns the current record's "user_id" value
 * @method varchar      getBanco()        Returns the current record's "banco" value
 * @method varchar      getAgencia()      Returns the current record's "agencia" value
 * @method varchar      getTipoConta()    Returns the current record's "tipo_conta" value
 * @method varchar      getOperacao()     Returns the current record's "operacao" value
 * @method varchar      getContaNumero()  Returns the current record's "conta_numero" value
 * @method varchar      getFavorecido()   Returns the current record's "favorecido" value
 * @method varchar      getCpf()          Returns the current record's "cpf" value
 * @method sfGuardUser  getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method DadoBancario setUserId()       Sets the current record's "user_id" value
 * @method DadoBancario setBanco()        Sets the current record's "banco" value
 * @method DadoBancario setAgencia()      Sets the current record's "agencia" value
 * @method DadoBancario setTipoConta()    Sets the current record's "tipo_conta" value
 * @method DadoBancario setOperacao()     Sets the current record's "operacao" value
 * @method DadoBancario setContaNumero()  Sets the current record's "conta_numero" value
 * @method DadoBancario setFavorecido()   Sets the current record's "favorecido" value
 * @method DadoBancario setCpf()          Sets the current record's "cpf" value
 * @method DadoBancario setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDadoBancario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dado_bancario');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('banco', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('agencia', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('tipo_conta', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('operacao', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('conta_numero', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('favorecido', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('cpf', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}