<?php

/**
 * BaseUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $original_url
 * @property varchar $short_url
 * 
 * @method varchar getOriginalUrl()  Returns the current record's "original_url" value
 * @method varchar getShortUrl()     Returns the current record's "short_url" value
 * @method Url     setOriginalUrl()  Sets the current record's "original_url" value
 * @method Url     setShortUrl()     Sets the current record's "short_url" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('url');
        $this->hasColumn('original_url', 'varchar', null, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('short_url', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}