<?php

/**
 * BaseConfiguracao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $chave
 * @property varchar $valor
 * 
 * @method varchar      getChave() Returns the current record's "chave" value
 * @method varchar      getValor() Returns the current record's "valor" value
 * @method Configuracao setChave() Sets the current record's "chave" value
 * @method Configuracao setValor() Sets the current record's "valor" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguracao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuracao');
        $this->hasColumn('chave', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('valor', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}