<?php

/**
 * BaseConta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property float $saldo
 * @property Usuario $Usuario
 * 
 * @method integer getUsuarioId()  Returns the current record's "usuario_id" value
 * @method float   getSaldo()      Returns the current record's "saldo" value
 * @method Usuario getUsuario()    Returns the current record's "Usuario" value
 * @method Conta   setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Conta   setSaldo()      Sets the current record's "saldo" value
 * @method Conta   setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conta');
        $this->hasColumn('usuario_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('saldo', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}