<?php

/**
 * BaseCustoClique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nclique
 * @property float $custo
 * 
 * @method integer     getNclique() Returns the current record's "nclique" value
 * @method float       getCusto()   Returns the current record's "custo" value
 * @method CustoClique setNclique() Sets the current record's "nclique" value
 * @method CustoClique setCusto()   Sets the current record's "custo" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustoClique extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('custo_clique');
        $this->hasColumn('nclique', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('custo', 'float', 11, array(
             'type' => 'float',
             'length' => 11,
             'scale' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}