<?php

/**
 * BasePaypal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $email
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method varchar     getEmail()       Returns the current record's "email" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Paypal      setUserId()      Sets the current record's "user_id" value
 * @method Paypal      setEmail()       Sets the current record's "email" value
 * @method Paypal      setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaypal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paypal');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('email', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}