<?php

/**
 * BaseCampanha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property float $orcamento
 * @property string $titulo
 * @property string $descricao
 * @property string $url_campanha
 * @property boolean $is_active
 * 
 * @method integer  getUsuarioId()    Returns the current record's "usuario_id" value
 * @method float    getOrcamento()    Returns the current record's "orcamento" value
 * @method string   getTitulo()       Returns the current record's "titulo" value
 * @method string   getDescricao()    Returns the current record's "descricao" value
 * @method string   getUrlCampanha()  Returns the current record's "url_campanha" value
 * @method boolean  getIsActive()     Returns the current record's "is_active" value
 * @method Campanha setUsuarioId()    Sets the current record's "usuario_id" value
 * @method Campanha setOrcamento()    Sets the current record's "orcamento" value
 * @method Campanha setTitulo()       Sets the current record's "titulo" value
 * @method Campanha setDescricao()    Sets the current record's "descricao" value
 * @method Campanha setUrlCampanha()  Sets the current record's "url_campanha" value
 * @method Campanha setIsActive()     Sets the current record's "is_active" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampanha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campanha');
        $this->hasColumn('usuario_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('orcamento', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('url_campanha', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}