<?php

/**
 * BaseRelato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $nome
 * @property varchar $site
 * @property varchar $imagem
 * @property string $texto
 * @property boolean $is_approved
 * 
 * @method varchar getNome()        Returns the current record's "nome" value
 * @method varchar getSite()        Returns the current record's "site" value
 * @method varchar getImagem()      Returns the current record's "imagem" value
 * @method string  getTexto()       Returns the current record's "texto" value
 * @method boolean getIsApproved()  Returns the current record's "is_approved" value
 * @method Relato  setNome()        Sets the current record's "nome" value
 * @method Relato  setSite()        Sets the current record's "site" value
 * @method Relato  setImagem()      Sets the current record's "imagem" value
 * @method Relato  setTexto()       Sets the current record's "texto" value
 * @method Relato  setIsApproved()  Sets the current record's "is_approved" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelato extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relato');
        $this->hasColumn('nome', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('site', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('imagem', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}