<?php

/**
 * BaseConta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property float $saldo
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $ContaOperacao
 * 
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method float               getSaldo()         Returns the current record's "saldo" value
 * @method sfGuardUser         getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getContaOperacao() Returns the current record's "ContaOperacao" collection
 * @method Conta               setUserId()        Sets the current record's "user_id" value
 * @method Conta               setSaldo()         Sets the current record's "saldo" value
 * @method Conta               setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method Conta               setContaOperacao() Sets the current record's "ContaOperacao" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conta');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('saldo', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('ContaOperacao', array(
             'local' => 'id',
             'foreign' => 'conta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}