<?php

/**
 * BaseStatusTransacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $status
 * @property Doctrine_Collection $Campanha
 * 
 * @method string              getStatus()   Returns the current record's "status" value
 * @method Doctrine_Collection getCampanha() Returns the current record's "Campanha" collection
 * @method StatusTransacao     setStatus()   Sets the current record's "status" value
 * @method StatusTransacao     setCampanha() Sets the current record's "Campanha" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatusTransacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status_transacao');
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Campanha', array(
             'local' => 'id',
             'foreign' => 'status_transacao_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}