<?php

/**
 * BaseResgate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $tipo_resgate_id
 * @property integer $status_id
 * @property float $valor
 * @property varchar $authkey
 * @property boolean $is_confirmed
 * @property sfGuardUser $sfGuardUser
 * @property TipoResgate $TipoResgate
 * @property Status $Status
 * @property Doctrine_Collection $UrlControle
 * @property Doctrine_Collection $ReferalControle
 * 
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method integer             getTipoResgateId()   Returns the current record's "tipo_resgate_id" value
 * @method integer             getStatusId()        Returns the current record's "status_id" value
 * @method float               getValor()           Returns the current record's "valor" value
 * @method varchar             getAuthkey()         Returns the current record's "authkey" value
 * @method boolean             getIsConfirmed()     Returns the current record's "is_confirmed" value
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method TipoResgate         getTipoResgate()     Returns the current record's "TipoResgate" value
 * @method Status              getStatus()          Returns the current record's "Status" value
 * @method Doctrine_Collection getUrlControle()     Returns the current record's "UrlControle" collection
 * @method Doctrine_Collection getReferalControle() Returns the current record's "ReferalControle" collection
 * @method Resgate             setUserId()          Sets the current record's "user_id" value
 * @method Resgate             setTipoResgateId()   Sets the current record's "tipo_resgate_id" value
 * @method Resgate             setStatusId()        Sets the current record's "status_id" value
 * @method Resgate             setValor()           Sets the current record's "valor" value
 * @method Resgate             setAuthkey()         Sets the current record's "authkey" value
 * @method Resgate             setIsConfirmed()     Sets the current record's "is_confirmed" value
 * @method Resgate             setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method Resgate             setTipoResgate()     Sets the current record's "TipoResgate" value
 * @method Resgate             setStatus()          Sets the current record's "Status" value
 * @method Resgate             setUrlControle()     Sets the current record's "UrlControle" collection
 * @method Resgate             setReferalControle() Sets the current record's "ReferalControle" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResgate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resgate');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tipo_resgate_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('status_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('valor', 'float', 11, array(
             'type' => 'float',
             'length' => 11,
             'scale' => '6',
             ));
        $this->hasColumn('authkey', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('is_confirmed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('TipoResgate', array(
             'local' => 'tipo_resgate_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('Status', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasMany('UrlControle', array(
             'local' => 'id',
             'foreign' => 'resgate_id'));

        $this->hasMany('ReferalControle', array(
             'local' => 'id',
             'foreign' => 'resgate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}