<?php

/**
 * BaseContaOperacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $conta_id
 * @property integer $tipo_operacao_id
 * @property float $valor
 * @property TipoOperacao $TipoOperacao
 * @property Conta $Conta
 * 
 * @method integer       getContaId()          Returns the current record's "conta_id" value
 * @method integer       getTipoOperacaoId()   Returns the current record's "tipo_operacao_id" value
 * @method float         getValor()            Returns the current record's "valor" value
 * @method TipoOperacao  getTipoOperacao()     Returns the current record's "TipoOperacao" value
 * @method Conta         getConta()            Returns the current record's "Conta" value
 * @method ContaOperacao setContaId()          Sets the current record's "conta_id" value
 * @method ContaOperacao setTipoOperacaoId()   Sets the current record's "tipo_operacao_id" value
 * @method ContaOperacao setValor()            Sets the current record's "valor" value
 * @method ContaOperacao setTipoOperacao()     Sets the current record's "TipoOperacao" value
 * @method ContaOperacao setConta()            Sets the current record's "Conta" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContaOperacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conta_operacao');
        $this->hasColumn('conta_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tipo_operacao_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('valor', 'float', 11, array(
             'type' => 'float',
             'length' => 11,
             'scale' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoOperacao', array(
             'local' => 'tipo_operacao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('Conta', array(
             'local' => 'conta_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}