<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * @property Doctrine_Collection $Resgate
 * 
 * @method string              getTipo()    Returns the current record's "tipo" value
 * @method Doctrine_Collection getResgate() Returns the current record's "Resgate" collection
 * @method Status              setTipo()    Sets the current record's "tipo" value
 * @method Status              setResgate() Sets the current record's "Resgate" collection
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Resgate', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}