<?php

/**
 * BaseCampanha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $titulo
 * @property string $url_campanha
 * @property integer $orcamento_id
 * @property string $maximo_orcamento_diario
 * @property string $auth_key
 * @property string $payment_method
 * @property string $paypal_id
 * @property boolean $is_payment_processed
 * @property integer $status_transacao_id
 * @property boolean $is_active
 * @property boolean $is_finished
 * @property datetime $end_date
 * @property Orcamento $Orcamento
 * @property StatusTransacao $StatusTransacao
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer         getUserId()                  Returns the current record's "user_id" value
 * @method string          getTitulo()                  Returns the current record's "titulo" value
 * @method string          getUrlCampanha()             Returns the current record's "url_campanha" value
 * @method integer         getOrcamentoId()             Returns the current record's "orcamento_id" value
 * @method string          getMaximoOrcamentoDiario()   Returns the current record's "maximo_orcamento_diario" value
 * @method string          getAuthKey()                 Returns the current record's "auth_key" value
 * @method string          getPaymentMethod()           Returns the current record's "payment_method" value
 * @method string          getPaypalId()                Returns the current record's "paypal_id" value
 * @method boolean         getIsPaymentProcessed()      Returns the current record's "is_payment_processed" value
 * @method integer         getStatusTransacaoId()       Returns the current record's "status_transacao_id" value
 * @method boolean         getIsActive()                Returns the current record's "is_active" value
 * @method boolean         getIsFinished()              Returns the current record's "is_finished" value
 * @method datetime        getEndDate()                 Returns the current record's "end_date" value
 * @method Orcamento       getOrcamento()               Returns the current record's "Orcamento" value
 * @method StatusTransacao getStatusTransacao()         Returns the current record's "StatusTransacao" value
 * @method sfGuardUser     getSfGuardUser()             Returns the current record's "sfGuardUser" value
 * @method Campanha        setUserId()                  Sets the current record's "user_id" value
 * @method Campanha        setTitulo()                  Sets the current record's "titulo" value
 * @method Campanha        setUrlCampanha()             Sets the current record's "url_campanha" value
 * @method Campanha        setOrcamentoId()             Sets the current record's "orcamento_id" value
 * @method Campanha        setMaximoOrcamentoDiario()   Sets the current record's "maximo_orcamento_diario" value
 * @method Campanha        setAuthKey()                 Sets the current record's "auth_key" value
 * @method Campanha        setPaymentMethod()           Sets the current record's "payment_method" value
 * @method Campanha        setPaypalId()                Sets the current record's "paypal_id" value
 * @method Campanha        setIsPaymentProcessed()      Sets the current record's "is_payment_processed" value
 * @method Campanha        setStatusTransacaoId()       Sets the current record's "status_transacao_id" value
 * @method Campanha        setIsActive()                Sets the current record's "is_active" value
 * @method Campanha        setIsFinished()              Sets the current record's "is_finished" value
 * @method Campanha        setEndDate()                 Sets the current record's "end_date" value
 * @method Campanha        setOrcamento()               Sets the current record's "Orcamento" value
 * @method Campanha        setStatusTransacao()         Sets the current record's "StatusTransacao" value
 * @method Campanha        setSfGuardUser()             Sets the current record's "sfGuardUser" value
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampanha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campanha');
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url_campanha', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('orcamento_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('maximo_orcamento_diario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('auth_key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('payment_method', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('paypal_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_payment_processed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('status_transacao_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_finished', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('end_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Orcamento', array(
             'local' => 'orcamento_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('StatusTransacao', array(
             'local' => 'status_transacao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'RESTRICT'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}