generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Conta
    theme:                 simpla
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          conta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=sfGuardUser, saldo]
        object_actions: 
          _edit: ~
        batch_actions: []
        actions: []
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
