<?php

/**
 * CampanhaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampanhaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampanhaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Campanha');
    }
}