<?php

/**
 * CampanhaControleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampanhaControleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampanhaControleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CampanhaControle');
    }
}