<?php

/**
 * ConfiguracaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfiguracaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfiguracaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configuracao');
    }
}