<?php

/**
 * ContaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conta');
    }
}