<?php

/**
 * ContaOperacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContaOperacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContaOperacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContaOperacao');
    }
}