<?php

/**
 * CustoCliqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustoCliqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustoCliqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustoClique');
    }
}