<?php

/**
 * CustoClique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CustoClique extends BaseCustoClique {

    public static function getCustoPorClique() {
        $custo = Doctrine::getTable('CustoClique')->createQuery('c')
                        ->orderBy('created_at desc')
                        ->limit(1)
                        ->execute()->getFirst();

        return ($custo) ? $custo->getCusto() / $custo->getNclique() : 0;
    }

}