<?php

/**
 * DadoBancarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DadoBancarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DadoBancarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DadoBancario');
    }
}