<?php

/**
 * Orcamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Orcamento extends BaseOrcamento {

    public function __toString() {
        parent::__toString();
        return $this->getDescricao();
    }

}