<?php

/**
 * OrcamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrcamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrcamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Orcamento');
    }
}