<?php

/**
 * RelatoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelatoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelatoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Relato');
    }
}