<?php

/**
 * ResgateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResgateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResgateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Resgate');
    }
}