<?php

/**
 * StatusTransacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusTransacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusTransacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusTransacao');
    }
}