<?php

/**
 * TipoOperacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoOperacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoOperacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoOperacao');
    }
}