<?php

/**
 * TipoResgateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoResgateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoResgateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoResgate');
    }
}