<?php

/**
 * TipoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoUsuario');
    }
}