<?php

/**
 * Url
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Url extends BaseUrl {

    public function getFullUrl() {
        return sfContext::getInstance()->getController()->genUrl('@resolve_url?url_id=' . $this->getShortUrl(), true);
    }

    public function getTotal() {
        $total = Doctrine::getTable('UrlControle')->createQuery('u')
                        ->select('count(u.url_id) as total')
                        ->where('u.url_id = ?', $this->getId())
                        ->groupBy('u.url_id')
                        ->execute()->getFirst();

        return ($total['total']) ? $total['total'] : 0;
    }

    public function getGanhos() {
        return $this->getTotal() * CustoClique::getCustoPorClique();
    }

    public static function getGanhosDoUsuario(sfGuardUser $usuario) {

        $urls = Doctrine::getTable('Url')->findByUserId($usuario->getId());

        $ganhos = 0;
        foreach ($urls as $url) {
            $ganhos += $url->getGanhos();
        }

        return $ganhos;
    }

    public static function getTotalAcessoByUser(sfGuardUser $usuario) {
        $urls = Doctrine::getTable('Url')->findByUserId($usuario->getId());
        $views = 0;
        
        if ($urls->count()) {
            foreach ($urls as $url) {
                $views += $url->getTotal();
            }
        }

        return $views;
    }

}