<?php

/**
 * UrlControleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UrlControleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UrlControleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UrlControle');
    }
}