<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario {

    public function getSaldoDisponivelParaResgate() {
        if ($this->getSfGuardUser()->count()) {
            return Url::getGanhosDisponivelDoUsuario($this->getSfGuardUser());
        }
        return 0;
    }

}