<?php

/**
 * ValidaUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValidaUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValidaUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValidaUsuario');
    }
}