# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: main, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: login, action: index }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
  
sf_guard_register:
  url:   /register
  param: { module: sfGuardRegister, action: index }
  
pos_register:
  url:   /pos-register
  param: { module: sfGuardRegister, action: posregister }
  
confirm_user:
  url:   /register/confirm/:id/*
  param: { module: sfGuardRegister, action: confirm }
  requirements:
    id: ~
  
profile:
  url:   /profile
  param: { module: profile, action: index }

profile_action:
  url:   /profile/:action/*
  param: { module: profile }
  
termos:
  url:   /termos-e-condicoes
  param: { module: termosecondicoes, action: index }
  
sobre:
  url:   /sobre-nos
  param: { module: sobrenos, action: index }
 
new_ad:
  url: /ad/new
  param: { module: profile, action: newad }
 
edit_ad:
  url: /ad/:id/edit
  param: { module: profile, action: editad }
  requirements:
    id: ~
 
wallet:
  url: /wallet
  param: { module: profile, action: wallet }
  
 
retirada:
  url: /retirada
  param: { module: retirada, action: index }
  
resolve_url:
  url:   /:url_id
  param: { module: main, action: resolve }
  requirements:
    url_id: ~
    
    
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }


default:
  url:   /:module/:action/*
