<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Encurtador
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {

    public function getConta() {
        $conta_usuario = Doctrine::getTable('Conta')->findOneByUserId($this->getId());

        if (is_null($conta_usuario)) {
            return false;
        } else {
            return $conta_usuario;
        }
    }

    public function getUsuario() {
        $usuario_cadastro = Doctrine::getTable('Usuario')->findOneByUserId($this->getId());

        if (is_null($usuario_cadastro)) {
            return false;
        } else {
            return $usuario_cadastro;
        }
    }

    public function criarConta() {
        if (!$this->getConta()) {
            $conta = new Conta();
            $conta->setUserId($this->getId());
            $conta->save();

            return $conta;
        }

        return $this->getConta();
    }

    public function criarUsuario($tipo_usuario) {
        if (!$this->getUsuario()) {
            $usuario = new Usuario();
            $usuario->setUserId($this->getId());
            $usuario->setTipoUsuarioId($tipo_usuario);
            $usuario->setReferalId(sfContext::getInstance()->getUser()->getAttribute('referal_id', NULL));
            $usuario->setReferalCode(md5(uniqid("")));
            $usuario->save();

            return $usuario;
        }

        return $this->getUsuario();
    }
    
    public function getTotalAcesso(){
        return Url::getTotalAcessoByUser($this);
    }
    
    public function getGanhoReferenciaTotal(){
        return $this->getTotalAcesso() * CustoClique::getCustoPorClique() * (Configuracao::getConfig('referencia_percent') / 100);
    }
    
    public function getGanhoReferenciaDisponivel(){
        return Url::getTotalAcessoByUserDisponivelReferencia($this) * CustoClique::getCustoPorClique() * (Configuracao::getConfig('referencia_percent') / 100);
    }
    
}