generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 simpla
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        username:       { label: Usuário }
        email_address:  { label: Email }
        first_name:     { label: Nome }
        last_login:     { label: Último login }
        password:       { label: Senha }
        password_again: { label: Repita a senha }
        is_active:      { label: Ativo }
      list:
        title:          Usuários
        display:        [=username, email_address, first_name, last_login]
        sort:           ~
        batch_actions:  []
      filter:
        display:        [username, email_address]
      form: 
        display:        [first_name, email_address, username, password, password_again, is_active, is_super_admin]
      edit:    
        title: Editar %%username%%
      new:     
        title: Novo usuário
