generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Orcamento
    theme:                 simpla
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          orcamento
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Orçamento de Campanhas
      filter:  ~
      form:    ~
      edit:    
        title: Editar Orçamento
      new:     
        title: Novo Orçamento
