Url:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    original_url: { type: varchar(), notnull: true }
    short_url: { type: varchar(255), notnull: true, unique: true }
    
UrlControle:
  actAs:
    Timestampable: ~
  columns:
    url_id: { type: integer(11) }
    resgate_id: { type: integer(11) }
    ipuser: { type: string(255) }
    is_rescued: { type: boolean, default: 0 }
    is_processed: { type: boolean, default: 0 }
    data_processado: { type: datetime }
  relations:
    Url: { onDelete: RESTRICT, onUpdate: RESTRICT }
    Resgate: { onDelete: RESTRICT, onUpdate: RESTRICT }

TipoUsuario:
  actAs:
    Timestampable: ~
  columns:
    tipo: { type: string(255) }
    
Usuario:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    tipo_usuario_id: { type: integer(11) }
    endereco: { type: string() }
    estado: { type: string(255) }
    cidade: { type: string(255) }
    cep: { type: string(255) }
    telefone: { type: string(255);}
  relations:
    sfGuardUser: { onDelete: CASCADE, onUpdate: CASCADE, local: user_id }
    TipoUsuario: { onDelete: RESTRICT, onUpdate: RESTRICT }
    
ValidaUsuario:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    chave: { type: string() }
    is_confirmed: { type: boolean, default: 0 }
  relations:
    sfGuardUser: { onDelete: CASCADE, onUpdate: CASCADE, local: user_id }
    
Conta:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    saldo: { type: "float(11,6)" }
  relations:
    sfGuardUser: { onDelete: CASCADE, onUpdate: CASCADE, local: user_id }
    
TipoOperacao:
  actAs:
    Timestampable: ~
  columns:
    tipo: { type: string(255) }
    
ContaOperacao:
  actAs:
    Timestampable: ~
  columns:
    conta_id: { type: integer(11) }
    tipo_operacao_id: { type: integer(11) }
    valor: { type: "float(11,6)" }
  relations:
    TipoOperacao: { onDelete: RESTRICT, onUpdate: RESTRICT }
    Conta: { onDelete: RESTRICT, onUpdate: RESTRICT }
    
Orcamento:
  actAs:
    Timestampable: ~
  columns:
    valor: { type: "float(11,6)" }
    quantidade: { type: integer(11) }
    descricao: { type: string(255) }
    
StatusTransacao:
  actAs:
    Timestampable: ~
  columns:
    status: { type: string(255) }
    
Campanha:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    titulo: { type: string(255) }
    url_campanha: { type: string() }
    orcamento_id: { type: integer(11) }
    maximo_orcamento_diario: { type: string(255) }
    auth_key: { type: string(255) }
    payment_method: { type: string(255) }
    paypal_id: { type: string(255) }
    is_payment_processed: { type: boolean, default: 0 }
    status_transacao_id: { type: integer(11) }
    is_active: { type: boolean, default: 1 }
    is_finished: { type: boolean, default: 0 }
    end_date: { type: datetime }
  relations:
    Orcamento: { onDelete: RESTRICT, onUpdate: RESTRICT }
    StatusTransacao: { onDelete: RESTRICT, onUpdate: RESTRICT }
    
CampanhaControle:
  actAs:
    Timestampable: ~
  columns:
    campanha_id: { type: integer(11) }
    ip_viewer: { type: string(255) }
    is_processed: { type: boolean, default: 0 }
    data_processado: { type: datetime }
    
CustoClique:
  actAs:
    Timestampable: ~
  columns:
    nclique: { type: integer(11) }
    custo: { type: "float(11,6)" } 

Status:
  actAs:
    Timestampable: ~
  columns:
    tipo: { type: string(255) }
    
TipoResgate:
  actAs:
    Timestampable: ~
  columns:
    tipo: { type: string(255) }
    descricao: { type: string() }
     
Resgate:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    tipo_resgate_id: { type: integer(11) }
    status_id: { type: integer(11) }
    valor: { type: "float(11,6)" }
    authkey: { type: varchar(255) }
    is_confirmed: { type: boolean, default: 0 }
  relations:
    sfGuardUser: { onDelete: RESTRICT, onUpdate: RESTRICT, local: user_id }
    TipoResgate: { onDelete: RESTRICT, onUpdate: RESTRICT }
    Status: { onDelete: RESTRICT, onUpdate: RESTRICT }
     
DadoBancario:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    banco: { type: varchar(255) }
    agencia: { type: varchar(255) }
    tipo_conta: { type: varchar(255) }
    conta_numero: { type: varchar(255) }
    favorecido: { type: varchar(255) }
    cpf: { type: varchar(255) }
  relations:
    sfGuardUser: { onDelete: RESTRICT, onUpdate: RESTRICT, local: user_id }
    
Paypal:
  actAs:
    Timestampable: ~
  columns:
    user_id: { type: integer(11) }
    email: { type: varchar(255) }
  relations:
    sfGuardUser: { onDelete: RESTRICT, onUpdate: RESTRICT, local: user_id }
